### ISSUE TITLE
2.12 version isn't showing up in the Maven repositories

### ISSUE THREAD

**Issue by AronT-TLV** [jliszka/probability-monad#16]
Thanks for this amazing library!

**Comment by rgugliel** [comment]
What is the status of the 2.12 publishing? That would be very nice!

**Comment by basarama** [comment]
I'm also curious about the status of this? I'm currently seeing issues with bucketHist when including the 2.11 version and do not see it when I include the source code directly.
`Caused by: java.lang.NoSuchMethodError: scala.math.BigDecimal.to(Lscala/math/BigDecimal;)Lscala/collection/immutable/Range$Partial;
	at probability_monad.Distribution$class.bucketedHistHelper(Distribution.scala:233)
	at probability_monad.Distribution$class.bucketedHist(Distribution.scala:221)
	at probability_monad.Distribution$$anon$1.bucketedHist(Distribution.scala:16)`

**Comment by jliszka** [comment]
Thanks for the bump! I just published version 1.0.3 for 2.10, 2.11 and 2.12. @basarama let me know if that fixes the issue you're seeing.

**Comment by basarama** [comment]
Yeah, that fixed the issues I was seeing! Thanks for keeping this package active @jliszka I'm having a blast trying to make my load testing more dynamic utilizing some of the models.

**Comment by jliszka** [comment]
Great to hear!
